In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

In [2]:
def get_transformed_data():
    print("Transformed Data")
    
    df = pd.read_csv('C:/Users/TANNERU/Downloads/train.csv/train.csv')
    #print(df)
    data = df.values.astype(np.float32)
    #print(data)
    
    np.random.shuffle(data)
    
    
    X = data[:,1:]
    Y = data[:,0].astype(np.int32)
    print("Innputs",X)
    print("output",Y)
    print(X.shape) #(42000, 784)
    print(Y.shape) #(42000,)
    
    
    Xtrain = X[:-1000]
    Xtest = X[-1000:]
    Ytrain = Y[:-1000]
    Ytest = Y[-1000:]
    print("Xtrain",Xtrain.shape)#(41000, 784)
    print("Xtest",Xtest.shape)#(1000, 784)
    print("Ytrain",Ytrain.shape)#(41000,)
    print("Ytest",Ytest.shape) #(1000,)
    
    
    mu = Xtrain.mean(axis = 0) #(784,)
    #print(mu)
    print(mu.shape)#(784,)
    
    
    #center the data
    Xtrain = Xtrain - mu
    Xtest = Xtest - mu
    print(Xtrain)
    print(Xtest)
    
    #transforming data
    pca = PCA()
    Ztrain = pca.fit_transform(Xtrain)
    Ztest = pca.transform(Xtest)
    print(Ztrain.shape)
    print(Ztest.shape)
    print(Ztrain)
    print(Ztest)
    
    #plot_cumulative_variance(pca)
    
    
    
    Ztrain = Ztrain[:,:300]
    Ztest = Ztest[:,:300]
    print(Ztrain.shape) #(41000, 300)
    print(Ztest.shape) # (1000, 300)
    
    
    #normalization
    mean = Ztrain.mean(axis = 0)
    std = Ztrain.std(axis = 0)
    
    Ztrain = (Ztrain - mean)/std
    Ztest = (Ztest - mean)/std
    
    
    return Ztrain,Ztest,Xtrain,Xtest

In [3]:
def get_normalized_data():
    print("Reading in and transforming data...")
    
    
    df = pd.read_csv('C:/Users/TANNERU/Downloads/train.csv/train.csv')
    #print(df)
    data = df.values.astype(np.float32)
    #print(data)
    
    np.random.shuffle(data)
    
    
    X = data[:,1:] #except 1 columns
    Y = data[:,0].astype(np.int32) #only 1st column
    print("Innputs",X)
    print("output",Y)
    print(X.shape) #(42000, 784)
    print(Y.shape) #(42000,)
    
    
    Xtrain = X[:-1000]
    Xtest = X[-1000:]
    Ytrain = Y[:-1000]
    Ytest = Y[-1000:]
    print("Xtrain",Xtrain.shape)#(41000, 784)
    print("Xtest",Xtest.shape)#(1000, 784)
    print("Ytrain",Ytrain.shape)#(41000,)
    print("Ytest",Ytest.shape) #(1000,)
    
    
    mu = Xtrain.mean(axis = 0) #(784,)
    std = Xtrain.std(axis = 0) 
    np.place(std,std == 0,1) # changes all values to 0,1
    print(np.place(std,std == 0,1))
    #print(mu)
    print(mu.shape)#(784,)
    
    
    #center the data
    Xtrain = (Xtrain - mu)/std
    Xtest = (Xtest - mu)/std
    print(Xtrain)
    print(Xtest)
    
    
    return Xtrain,Xtest,Ytrain,Ytest
    
    
    
    
    


In [4]:
get_normalized_data()

Reading in and transforming data...
Innputs [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
output [8 2 6 ... 6 8 2]
(42000, 784)
(42000,)
Xtrain (41000, 784)
Xtest (1000, 784)
Ytrain (41000,)
Ytest (1000,)
None
(784,)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([8, 2, 6, ..., 0, 6, 3]),
 array([5, 4, 1, 0, 1, 0, 3, 3, 0, 3, 2, 0, 3, 7, 7, 6, 9, 1, 2, 1, 1, 6,
        0, 0, 2, 8, 8, 0, 4, 3, 2, 9, 5, 9, 6, 7, 4, 2, 7, 8, 2, 0, 8, 7,
        3, 7, 5, 9, 6, 2, 9, 4, 7, 9, 8, 4, 8, 4, 5, 9, 9, 3, 9, 4, 4, 1,
        4, 2, 3, 8, 0, 0, 8, 7, 9, 8, 9, 7, 0, 3, 2, 7, 9, 7, 5, 4, 3, 6,
        7, 7, 5, 7, 6, 0, 1, 9, 8, 4, 0, 7, 7, 6, 8, 9, 5, 4, 0, 3, 3, 7,
        7, 9, 8, 1, 9, 6, 3, 5, 8, 0, 6, 3, 3, 8, 0, 6, 4, 3, 6, 1, 3

In [5]:
def forward(X,w,b):
    #softmax
    a = X.dot(w)+b
    expA = np.exp(a)
    y = expA/expA.sum(axis = 1,keepdims = True)
    return y



def predict(p_y):
    return np.argmax(p_y,axis = 1)


def error_rate(p_y,t):
    prediction = predict(p_y)
    return np.mean(prediction != t)


def cost(p_y,t):
    tot = -t*np.log(p_y)
    return tot.sum()


def gradw(t,y,X):
    return X.T.dot(t-y)


def gradb(t,y):
    return (t-y).sum(axis = 0)


def y2indicator(y):
    N = len(y)
    y = y.astype(np.int32)
    ind = np.zeros((N,10))
    for i in range(N):
        ind[i,y[i]] = 1
    return ind






def benchmark_full():
    Xtrain,Xtest,Ytrain,Ytest = get_normalized_data()
    
    
    N,D = Xtrain.shape
    Ytrain_ind = y2indicator(Ytrain)
    Ytest_ind = y2indicator(Ytest)
    
    
    w = np.random.randn(D,10)/np.sqrt(D)
    b = np.zeros(10)
    
    lltrain = []
    lltest = []
    CRtest = []
    
    
    lr = 0.00004
    reg = 0.01
    
    
    for i in range(500):
        #traning
        p_y = forward(Xtrain,w,b)
        
        ll = cost(p_y,Ytrain_ind) #train cost
        lltrain.append(ll)
        
        #testing
        
        p_y_test = forward(Xtest,w,b)
        
        cr = cost(p_y_test,Ytest_ind) #test cost
        lltest.append(cr)
        
        
        err = error_rate(p_y_test,Ytest)
        CRtest.append(err)
        
        
        w += lr*(gradw(Ytrain_ind,p_y,Xtrain)-reg*w)
        b += lr*(gradb(Ytrain_ind,p_y)-reg*b)
        
        if i % 10 == 0:
            print("iteration :",i,"Cost:",ll)
            print("error",err)
            
    p_y = forward(Xtrain,w,b)
    print("Final error rate",error_rate(p_y,Ytest))
    iters  = range(len(lltrain))
    plt.plot(iters,lltrain,iters,lltest)
    plt.show()
    plt.plot(CRtest)
    plt.show()
        
        

        

        
    
    
def benchmark_pca():
    Xtrain, Xtest, Ytrain, Ytest = get_transformed_data()
    print("Performing logistic regression...")

    N, D = Xtrain.shape#(41000,)
    print(N,D)
    Ytrain  =  Ytrain.astype(np.int32)
    Ytest = Ytest.astype(np.int32)
    
    
    Ytrain_ind = np.zeros((N, 10))
    for i in range(N):
        Ytrain_ind[i, Ytrain[i]] = 1

    Ntest = len(Ytest)
    print(Ntest)
    Ytest_ind = np.zeros((Ntest, 10))
    for i in range(Ntest):
        Ytest_ind[i, Ytest[i]] = 1

    W = np.random.randn(D, 10) / np.sqrt(D)
    b = np.zeros(10)
    LL = []
    LLtest = []
    CRtest = []

    # D = 300 -> error = 0.07
    lr = 0.0001
    reg = 0.01
    for i in range(200):
        #training
        p_y = forward(Xtrain, W, b)
        # print "p_y:", p_y
        ll = cost(p_y, Ytrain_ind)
        LL.append(ll)
        
        #testing
        p_y_test = forward(Xtest, W, b)
        lltest = cost(p_y_test, Ytest_ind)
        LLtest.append(lltest)

        #error rate
        err = error_rate(p_y_test, Ytest)
        CRtest.append(err)

        W += lr*(gradW(Ytrain_ind, p_y, Xtrain) - reg*W)
        b += lr*(gradb(Ytrain_ind, p_y) - reg*b)
        if i % 10 == 0:
            print("Cost at iteration %d: %.6f" % (i, ll))
            print("Error rate:", err)

    p_y = forward(Xtest, W, b)
    print("Final error rate:", error_rate(p_y, Ytest))
    iters = range(len(LL))
    plt.plot(iters, LL, iters, LLtest)
    plt.show()
    plt.plot(CRtest)
    plt.show()


In [6]:
benchmark_pca()

Transformed Data
Innputs [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
output [3 5 1 ... 6 4 2]
(42000, 784)
(42000,)
Xtrain (41000, 784)
Xtest (1000, 784)
Ytrain (41000,)
Ytest (1000,)
(784,)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(41000, 784)
(1000, 784)
[[-1.92687332e+02 -6.92293213e+02 -2.34037766e+02 ... -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [ 2.39956512e+02 -7.05968994e+02 -4.08868904e+01 ...  1.30984886e-03
  -2.54572515e-04 -2.43882623e-05]
 [-9.66904724e+02 -6.74320740e+02  1.79359604e+02 ... -1.08956557e-03
  -1.06121646e-04 -4.63867291e-05]
 ...
 [-6.20596428e+01  4.52255310e+02  1.578

IndexError: index -12 is out of bounds for axis 1 with size 10

In [ ]:
benchmark_full()

Reading in and transforming data...
Innputs [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
output [3 3 5 ... 5 9 0]
(42000, 784)
(42000,)
Xtrain (41000, 784)
Xtest (1000, 784)
Ytrain (41000,)
Ytest (1000,)
None
(784,)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
iteration : 0 Cost: 104135.82042408394
error 0.909
iteration : 10 Cost: 14843.63969950367
error 0.121
iteration : 20 Cost: 11759.3668167405
error 0.092
iteration : 30 Cost: 11311.81385821835
error 0.099
iteration : 40 Cost: 11510.255627965877
error 0.109
iteration : 50 Cost: 10431.144855521445
error 0.095
iteration : 60 Cost: 10215.811398413027
error 0.095
it